### ISSUE TITLE
helper function for files produced with html_print

### ISSUE THREAD

**Issue by timelyportfolio** [wch/webshot#10]
I think a very useful helper function with `webshot` would be something that provides the valid `url` for a local file created with `htmltools::html_print`.  I doubt this works on non-Windows but something like this might be very helpful especially with `htmlwidgets` (see https://github.com/ramnathv/htmlwidgets/issues/95).

```r
library(leaflet)
library(htmltools)
library(webshot)

tagList(
  tags$h1( 'Leaflet Map for Screenshot' )
  ,leaflet() %>% addTiles() %>% fitBounds(0, 40, 10, 50)
) %>%
  html_print %>%
  # get forward slash on windows
  normalizePath(.,winslash="/") %>%
  # replace drive:/ with drive:// so C:/ becomes C://
  gsub(x=.,pattern = ":/",replacement="://") %>%
  # appends file:/// to make valid uri
  paste0("file:///",.) %>%
  # screenshot it for lots of good reasons
  webshot( file = "stream_screen.png", delay = 3 )
```

![image](https://cloud.githubusercontent.com/assets/837910/7050062/4c1747d4-dde4-11e4-98c8-87cf4ecb9bc5.png)

**Comment by timelyportfolio** [comment]
@wch is this worth exploring/demonstrating in `webshot` or would it fit better in `htmlwidgets`

**Comment by yihui** [comment]
This has been (almost) done in the current master branch of yihui/knitr. Simply try an arbitrary widget in R Markdown, and compile it to a non-HTML output format:

```r
leaflet() %>% addTiles() %>% fitBounds(0, 40, 10, 50)
```

I have not supported arbitrary HTML objects (such as `tagList()`), though. See more info at https://github.com/yihui/knitr/blob/master/NEWS.md

**Comment by yihui** [comment]
Oh I forgot to mention that requires this branch of htmlwidgets: https://github.com/ramnathv/htmlwidgets/pull/191

**Comment by timelyportfolio** [comment]
Great, I'll check it out there and close this issue here.  I only used `tagList` to ease `html_print`.  Thanks!

**Comment by wch** [comment]
I can see how this might be useful outside of knitr as well.

@timelyportfolio I think that this functionality would conceptually be a nice fit for inclusion in htmlwidgets. However, because webshot has some unusual external dependencies, it could make sense to include that functionality in the webshot package itself.

**Comment by yihui** [comment]
Definitely agree this can be useful outside knitr.

**Comment by timelyportfolio** [comment]
Ok, happy to work something up, but know quest for CRAN might push it to next release.  Let me know if you want to squeeze it in and I'll be glad to work on it.

**Comment by wch** [comment]
Yup, I just submitted to CRAN so it would have to be for the next version.
:)
