### ISSUE TITLE
mapshot Error refers to webshot: Error in (function (url = NULL, file = "webshot.png", vwidth = 992, vheight = 744,  : webshot.js returned failure value: 1

### ISSUE THREAD

**Issue by KathaRRRina** [wch/webshot#112]
Hi there,
as I couldn't find a solution with this issue https://github.com/r-spatial/mapview/issues/419, I got the advice to try it here.
This  is my problem:

I am creating a Report with R Markdown and a part of it is based on maps that I create with leaflet. Then I use mapshot to create a jpg and save the map. So that I can load and show the jpg in the Report.

So far this worked fine, but since my last R update (Version 4.2.0) mapshot creates an Error. And unfortunately I can hardly find any support on this error online. Here is my reproducible example:

´´´ 
library("leaflet")
library("mapview")

m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
m 
mapshot(m, file = "C:/Rplot2.jpg") 
´´´

This is the Error I get:

´´´
Could not load  c:%5CUsers%5CVedi%5CAppData%5CLocal%5CTemp%5CRtmpqcG5qY%5Cfile36844d44770d.html
Error in (function (url = NULL, file = "webshot.png", vwidth = 992, vheight = 744,  : 
  webshot.js returned failure value: 1
´´´

I have tried:
- reinstallation of the needed packages, also of webshot
- reinstallation of R and R Studio

The problem occurs on a laptop and on a server I  use.

Any help is much appreciated!

**Comment by wch** [comment]
Does this work?

```R
library(webshot)
webshot("https://www.r-project.org/", "r.png")
```

I suggest also trying to use webshot for a local HTML file, like this (replacing `c:/..../file.html` with the path to an actual HTML file on your computer):

```R
webshot("c:/..../file.html", "test.png")
```

If those work, then the problem is likely to be related to mapshot.

**Comment by KathaRRRina** [comment]
> ```r
> webshot("c:/..../file.html", "test.png")
> ```

Hi wch,
thank you for your answer! Your webshot example works for me. Where can I post issues that relate to mapshot? (I am new here)

**Comment by wch** [comment]
I think the original issue that you filed on the mapview repository is probably a good place to continue.

**Comment by carlinstarrs** [comment]
I am getting this same error with webshot 0.5.3. Downgrading to 0.5.2 seemed to fix it for some reason. This was all I was trying to run (from the kableExtra package): 

mtcars %>%
  kable() %>%
  kable_styling() %>%
  save_kable("test.png")

**Comment by wch** [comment]
Hm, I think there's a good chance this is due to #110.

**Comment by wch** [comment]
I just submitted a new version to CRAN with a fix for this issue.

**Comment by c-brendel** [comment]
I just checked my code again and now it works with webshot 0.5.4! Thanks!
