### ISSUE TITLE
cliprect = "viewport" in function webshot gives an error

### ISSUE THREAD

**Issue by heeringa0** [wch/webshot#119]
Using cliprect = "viewport" in the function webshot gives an error:

Warning: Error in ||: 'length = 4' in coercion to 'logical(1)'

Example:
webshot("https://www.r-project.org/", "r-viewport.png", cliprect = "viewport")

(example taken from http://wch.github.io/webshot/ ).

No error occurs for:
webshot("https://www.r-project.org/", "r-viewport.png")

but I need the viewport clipping, so I hope there is a solution for this problem.

**Comment by wch** [comment]
This is probably due to a change in R 4.3. See here for a bit more info:
https://www.jumpingrivers.com/blog/whats-new-r43/

This was fixed by #117 but we haven't had a release since then. You can install this by running:

```R
remotes::install_github("wch/webshot")
```

We can make a new release some time next week.

**Comment by heeringa0** [comment]
Thanks, installing from GitHub solved the problem.

A new release would be wonderful.

________________________________

**Comment by wch** [comment]
The new version, 0.5.5, is on CRAN. It may take a few days for binary packages to built for Mac and Windows.
https://cran.r-project.org/web/packages/webshot/
