### ISSUE TITLE
appshot vignette example not working

### ISSUE THREAD

**Issue by markriseley** [wch/webshot#12]
I can't make appshot work on my windows PC. I just installed phantomjs and have successfully run the first couple of webshot examples on the rstudio homepage. Here's console output from when I try the appshot() vignette example (which I ran after clearing workspace and restarting R): 

    > appdir <- system.file("examples", "01_hello", package="shiny")
    > appshot(appdir, "01_hello.png")
    Warning PhantomJS v2.0 not yet released. There will not be any official support for any bugs until stable version is released!
    Error in file(con, "r") : cannot open the connection
    In addition: Warning message:
    In file(con, "r") :
    cannot open file 'C:\Users\Mark\AppData\Local\Temp\RtmpeI2i8Z\pid207878a65777': No such file or directory

However I do have this (empty) file in the same temp directory: 
'file207878583cc9'.

devtools::session_info()
Session info ------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.1.2 (2014-10-31)
 system   x86_64, mingw32             
 ui       RStudio (0.99.441)          
 language (EN)                        
 collate  English_United Kingdom.1252 
 tz       Europe/London               

Packages ----------------------------------------------------------------------------------
 package   * version  date       source                      
 bitops      1.0-6    2013-08-17 CRAN (R 3.1.2)              
 devtools    1.8.0    2015-05-09 CRAN (R 3.1.3)              
 digest      0.6.8    2014-12-31 CRAN (R 3.1.2)              
 git2r       0.10.1   2015-05-07 CRAN (R 3.1.3)              
 magrittr    1.5      2014-11-22 CRAN (R 3.1.2)              
 memoise     0.2.1    2014-04-22 CRAN (R 3.1.2)              
 RCurl       1.95-4.6 2015-04-24 CRAN (R 3.1.3)              
 rversions   1.0.0    2015-04-22 CRAN (R 3.1.3)              
 webshot   * 0.2.1    2015-06-08 Github (wch/webshot@810f302)
 XML         3.98-1.2 2015-05-31 CRAN (R 3.1.3)

**Comment by yihui** [comment]
I have tweaked several things on Windows and it will be great if you can test the current version. At least this example works for me on Windows now.
