### ISSUE TITLE
incorrect formatting with rmdshot

### ISSUE THREAD

**Issue by RKonstantinR** [wch/webshot#121]
I created a quarto document using callout blocks and grid. 

When I render this document in rstudio the formatting is displayed correctly:
![изображение](https://github.com/rstudio/webshot2/assets/38781076/dad64f77-4b23-4b3a-bc15-f445797b8ce0)

But when I use rmdshot formatting is not displayed correctly:
![изображение](https://github.com/rstudio/webshot2/assets/38781076/bb8d265b-454c-4f4d-9102-2894dce75a9a)

Is there a way to fix this?

Quarto doc:
``````
---
title: "repex"
format:
  html:
    embed-resources: true
    page-layout: full
editor: visual
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(echarts4r)
library(tibble)

```

::: grid
::: g-col-2
::: {.callout-note icon="false"}
## one

1
:::
:::

::: g-col-2
::: {.callout-note icon="false"}
## two

2
:::
:::

::: g-col-2
::: {.callout-note icon="false"}
## three

3
:::
:::

::: g-col-2
::: {.callout-note icon="false"}
## four

4
:::
:::

::: g-col-2
::: {.callout-note icon="false"}
## five

5
:::
:::

::: g-col-2
::: {.callout-note icon="false"}
## six

6
:::
:::
:::

::: grid
::: g-col-2
::: border
::: ticker_name
TEXT
:::

::: board_name
SUBTEXT
:::
:::

::: {.callout-tip appearance="minimal"}
foo: bar

foo: bar

foo: bar
:::
:::

::: g-col-10
```{r, echo=FALSE, message=FALSE, warning=FALSE}

plot(mtcars$cyl)

```
:::
:::

``````

R script:
```
library(webshot)

webshot::rmdshot("test.qmd", file = "tst.png")
```

**Comment by wch** [comment]
Sorry, this probably is not fixable with webshot, because it uses a very old headless browser which hasn't been developed since 2018. I'll make this clearer in the README. Please use webshot2 instead.
