### ISSUE TITLE
UTF-8 encoding error

### ISSUE THREAD

**Issue by TCantellow** [wch/webshot#123]
When using webshot to capture a .hmtl table exported by the tab_model function from sjPlot, it inteprets the "x" character used when showing the interaction effect between two variable names as "Ã-". 

I have tried specifying the tab_model function to save the .hmtl table using UTF-8 encoding, but the error persists. 

I have tested every step of the process of exporting, saving, and capturing these .html tables, and can confirm that the error occurs with the webshot() function. 

I am using Windows 10, and have also set  RStudio's default encoding as UTF-8. I have also opened the .html file in browsers, and the encoding is correct. The error only occurs when using the webshot() function. 

Any help would be greatly appreciated.

**Comment by wch** [comment]
webshot uses PhantomJS, which is a headless browser that stopped development in 2018. It is likely that the problem is due to the very old and unsupported browser. Please use [webshot2](https://github.com/rstudio/webshot2), which uses Chromium-based browsers.
