### ISSUE TITLE
Check that phantomjs is installed?

### ISSUE THREAD

**Issue by ismayc** [wch/webshot#25]
Is there a way to include something like what I have for packages

```
needed_pkgs <- c("nycflights13", "dplyr", "ggplot2", "knitr", 
  "devtools", "ggplot2", "webshot")
new.pkgs <- needed_pkgs[!(needed_pkgs %in% installed.packages())]

if (length(new.pkgs)) {
  install.packages(new.pkgs, repos = "http://cran.rstudio.com")
}
```

to check to see if phantomjs is installed?  Right now I just have a commented out

```
#webshot::install_phantomjs()
```

in the same chunk as my chunk above but it would be nice if I could run a check and install it if needed.

**Comment by vnijs** [comment]
On a mac you can use `Sys.which("phantomjs")`. Won't work on Windows though unless phanomjs is in your path

**Comment by ismayc** [comment]
Thanks!  The mac check will work for me for now.

**Comment by vnijs** [comment]
Just noticed `webshot:::find_phantom()`. Should work on both Mac and Windows

**Comment by ismayc** [comment]
Thanks, @vnijs!  I completely over-looked that.

**Comment by yihui** [comment]
Yep, just check if `webshot:::find_phantom()` is NULL.

**Comment by coatless** [comment]
Would you folks be interested in a PR with a modified version of `install_phantomjs()` that checks if it is already installed at the given version? Or an **exported** package function that detects if `phantomjs` is present?

**Comment by wch** [comment]
@coatless Sure, a modified `install_phantomjs` sounds like a good idea. Maybe with an argument `force` which defaults to `FALSE`?

**Comment by coatless** [comment]
@wch Great! I'll submit a PR to handle this.
