### ISSUE TITLE
add option for better render resolution ( code included)

### ISSUE THREAD

**Issue by giko45** [wch/webshot#26]
Hi,
To get a better resolution in renderd images  I usually change in the webshot.js file (`system.file("webshot.js", package="webshot")`)

the follwoing line
`casper.start(url).viewport(opts.vwidth, opts.vheight);`
to 
`casper.start(url).viewport(opts.vwidth, opts.vheight).zoom(2);`

Could that be added as a option instead?

**Comment by wch** [comment]
Sounds like a good idea. It would also be nice to do HiDPI (Retina-resolution) screenshots (i.e. with a `window.devicePixelRatio`) which could differ from a zoomed screenshot because a page may load different, higher-res images when it thinks it's rendering on a HiDPI device.

**Comment by giko45** [comment]
Hi,

I checked the code you checked and noticed that you also changed the viewport.  I only did use casper.start(url).viewport(opts.vwidth, opts.vheight).zoom(2) without changeing the viewport.

Wy is the change in viewport needed. Does that not lead to changed fontsizes etc?

**Comment by wch** [comment]
Maybe we have a different understanding of what the zoom is supposed to do, but without changing the viewport, the "virtual" viewport size changes when you zoom, so the end result can  have a very different layout.

For example, here's the R homepage taken with no zoom:
![r-normal](https://cloud.githubusercontent.com/assets/86978/18747250/e1399924-8091-11e6-9bc0-2fd59ca55203.png)

Here it is with zoom=2, but no changing of the viewport. The pixel dimensions are the same but the layout changes:
![r-small-zoomed-no-viewport](https://cloud.githubusercontent.com/assets/86978/18747259/f25205e8-8091-11e6-859b-6720f9ff7c83.png)

Here it is with zoom=2 and a doubling of the viewport (you may need to open this in a new window to see how it differs from the first image:
![r-small-zoomed](https://cloud.githubusercontent.com/assets/86978/18747299/2c30004e-8092-11e6-95f1-f116ef2baf82.png)
