### ISSUE TITLE
screenshot for googlesheet

### ISSUE THREAD

**Issue by prasoonsrivas** [wch/webshot#29]
Hi 
It is a great package help a lot, great job,  But while taking the snapshot of googlesheet it stuck on gmail login page and webshot captured a login screen .... please help

**Comment by wch** [comment]
I think this would probably require passing in Javascript code to drive the login, but that's a non-trivial task.

**Comment by prasoonsrivas** [comment]
Agree with you @wch can you light the way to pass java script code drive , because i am not getting any clue for that. (hand tight in javacode script )  :)
