### ISSUE TITLE
Vectorize webshot

### ISSUE THREAD

**Issue by cuche27** [wch/webshot#32]
Hello, 

I want to convert a lot of html pages generated with dygraphs in order to generate a gif animation.  But for now, each call to webshot takes about three seconds to execute. 

After doing a few tests, it looks like most of the time is spent to initialize phantomjs. I think it would save a lot of time to be able to pass a vector of URL and file names to the script `webshot.js` and to use `casper.each` to do the job.

**Comment by wch** [comment]
Closed by #33.
