### ISSUE TITLE
Selector not 100% accurate

### ISSUE THREAD

**Issue by fabiangehring** [wch/webshot#37]
hi,

In this mre I get the desired png, but at the very top of the picture the filter and search field are visible, even though they are not part of the selector:

```
data <- data.frame(a = 1:9, b = c(5, 2, 3, 9, 4, 3, 1, 5, 3))
table <- datatable(data)
htmlwidgets::saveWidget(widget = table, file = "table.html")
webshot("table.html", file = "table.png", selector = "#DataTables_Table_0", expand = 10, zoom = 5)
```

Screenshot:
![image](https://cloud.githubusercontent.com/assets/13698134/22663165/e405228c-ecab-11e6-82b5-08f7801b2cbc.png)

**Comment by fabiangehring** [comment]
Came accross this issue again. Any news on this?

**Comment by wch** [comment]
It's because you're using `expand=10`.
