### ISSUE TITLE
Webshot R-Package not working at all

### ISSUE THREAD

**Issue by talithafs** [wch/webshot#38]
I'm trying to use webshot for R, but even the simplest examples won't work. For instance,

```
URL <- "http://rstudio.github.io/leaflet/"
webshot(URL, delay = 0.5)
```
doesn't produce any output. This example is in the package vignette. None of the examples there works, actually.

I have phantomjs installed under AppData/Roaming, as it should. What is happening? It seems that it works for everyone else and my problem is undocumented : ( So I don't have a clue of what is going on. 

Here is my R session info:

```
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] magrittr_1.5      rsconnect_0.4.2.2 tools_3.3.3      
[4] jsonlite_1.2      webshot_0.4.0
```

If you need more info, let me know.

Thanks in advance.

**Comment by wch** [comment]
Is it not producing a file called `webshot.png` in your working directory?

**Comment by talithafs** [comment]
Like magic, it suddenly started working. I don't have a clue of what happened, but I'm closing this issue. I'm sorry to bother you : (

**Comment by wch** [comment]
No worries, I'm glad it's working.
