### ISSUE TITLE
webshot: export web element type id (not class)

### ISSUE THREAD

**Issue by mario-metriplica** [wch/webshot#39]
I need to export to png files some web elements from a specific site with webshot R library.

First, installing and loading libraries:

```
install.packages("webshot",dependencies = TRUE)
library(webshot)
webshot::install_phantomjs()
```

I'm testing webshot() with www.google.es URL. It works well:

`webshot("https://www.google.es/","google.png", selector="#hplogo")
`

But If I want to export to PNG image the search engine element (id web element), I write the following code:

`webshot("https://www.google.es/","google.png", selector=".tsf-p")
`

What is wrong?

__PHANTOM ERROR: CasperError: No element matching selector found: .tsf-p
TRACE:
 -> phantomjs://platform/casper.js: 1066 (in function getElementBounds)
 -> phantomjs://code/webshot.js: 137
 -> undefined: 0 (in function map)
 -> phantomjs://code/webshot.js: 136 (in function findClipRect)
 -> phantomjs://code/webshot.js: 85
 -> phantomjs://platform/casper.js: 2188 (in function _check)
Error in webshot("https://www.google.es/", "google.png", selector = ".tsf-p") : 
  webshot.js returned failure value: 1
In addition: Warning message:_
running command '"C:\Users\Mario Martínez\AppData\Roaming/PhantomJS/phantomjs.exe" "C:/User......"_

**Comment by wch** [comment]
It's likely that there's no div with that class. For example, when I load www.google.es in Chrome, it's there, but when I have it emulate a mobile device, there is no div with class `tsf-p`. I think that google.es is serving different content to PhantomJS than it would to (for example) Chrome.

Webshot currently doesn't have a way to set the User-Agent, but if it did, that might be a way to work around it.

**Comment by mario-metriplica** [comment]
thanks for the answer @wch.

**Comment by wch** [comment]
I filed an issue for the user-agent option, so I'm closing this.
