### ISSUE TITLE
addWebGLHeatmap layer from leafletextras won't be saved as a png

### ISSUE THREAD

**Issue by VincentPe** [wch/webshot#45]
Please help me with the following.

I am making a heatmap using leaflet and addWebGLHeatmap. This works fine, until I try and save the plot as PNG using webshot. See the code below. It saves the terrain layer but does not show the heating on the saved image, while it does show in the viewer.

library(leaflet) 
library(leaflet.extras) 
library(mapview) 
library(dplyr)

testframe <- data.frame(lat = rnorm(500, mean = 50, sd = 0.1), 
                                       lon = rnorm(500, mean = 4, sd = 0.05)) 

testmap <- leaflet() %>% 
   addProviderTiles("Stamen.Terrain") %>% 
   setView(map, lng = 4.0,lat = 50.0 ,zoom = 9) 

save <- testmap %>% 
   addWebGLHeatmap(data = testframe, lng=~lon, lat=~lat, size = 4000, opacity = 0.60, intensity = 0.25) mapshot(save, file = "heatmap.png"))

Hope anyone is able to help.

**Comment by wch** [comment]
PhantomJS doesn't support WebGL, so webshot doesn't either. At some point we'll probably switch to use headless Chrome, which appears to have some support for WebGL, but that won't happen for at least a few more months.
https://bugs.chromium.org/p/chromium/issues/detail?id=617551
