### ISSUE TITLE
htmlwidgets element  not showing in webshot

### ISSUE THREAD

**Issue by Bryant-zhu** [wch/webshot#50]
hi there 
 I have been using the web shot as an final step of my automated daily report for a while.
 it's been working for my previous web shot of markdown made of high charter and other screen shot.

but recently I have try out the flexdashboard in R  for better visual effect. 
then when I try webshot, it turns out like this.
 all the element made of HTML widgets is not showing.

 
![snipaste_2017-12-22_11-22-13](https://user-images.githubusercontent.com/13691830/34284324-ffe33e2a-e70b-11e7-93ed-4da453bd531a.png)

is there any way of fixing this ? that would be really helpful.

**Comment by wch** [comment]
I think HTML Widgets in general should work. Can you supply a minimal reproducible example?
