### ISSUE TITLE
Link embedded in the image?

### ISSUE THREAD

**Issue by privefl** [wch/webshot#56]
Is it possible to embed the link in the image so that you can click on the image to browse the link?
I imagine that this is possible in HTML. [It is](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_image).

Thanks for this great package!

**Comment by wch** [comment]
Webshot outputs a PNG file. If you want to put it in a HTML web page and make it clickable, you can add the appropriate `<a href="...">` tag around the `<img>` tag, as in the example you provided.
