### ISSUE TITLE
install_phantomjs dir on package path

### ISSUE THREAD

**Issue by wildintellect** [wch/webshot#74]
The documentation for install_phantomjs() states 
> "If these directories are not writable, the directory ‘PhantomJS’ under the installation directory of the webshot package will be tried"

But looking at the code it does not actually try this directory. 
This line in utils.R fails if PhantomJS folder doesn't already exist as system.file will return an empty character string.
`path <- c(path, system.file('PhantomJS', package = 'webshot'))`
Needs to be something like 
`path <- c(path, file.path(system.file(package = 'webshot'),'PhantomJS'))`

_Tested this on a Linux machine._

**Comment by bubifengyun** [comment]
Please add installed-dir for webshot::install_phantomjs() in linux. @wch Thank you.
