### ISSUE TITLE
PhantomJS Archived

### ISSUE THREAD

**Issue by chris-prener** [wch/webshot#75]
I wanted to ask about the [reliance on PhantomJS](https://bookdown.org/yihui/rmarkdown/interactive-documents.html) that `webshot` provides to `knitr`. I saw today that [PhantomJS has been archived](https://github.com/ariya/phantomjs/issues/15344), and was wondering if there were plans in place to continue to support embedded screen-shots from HTML widgets in `knitr`. Everything seems to work OK right now, but am wondering about the future. Thanks for your thoughts on this!

**Comment by znmeb** [comment]
I wonder if Selenium WebDriver can do this. It's becoming a W3C standard (as "WebDriver" - https://w3c.github.io/webdriver/) and there are already R packages that can drive it (http://ropensci.github.io/RSelenium/).

**Comment by wch** [comment]
We're currently working on something that will eliminate the need for PhantomJS, so stay tuned...

**Comment by chris-prener** [comment]
Awesome - thanks @wch!

**Comment by randomgambit** [comment]
hello there! any updates on this? I cannot install phantomJS in my corporate environment... :( THanks!

**Comment by wch** [comment]
@randomgambit Hopefully we'll have something available in the next couple of months.

**Comment by randomgambit** [comment]
@wch hi there! are we making good progress here? :D

**Comment by wch** [comment]
@randomgambit Check out https://github.com/rstudio/webshot2 and let us know how it goes.

**Comment by randomgambit** [comment]
a cool stuff!! thanks buddy i ll try asap
