### ISSUE TITLE
look a little harder for phantom in Windows

### ISSUE THREAD

**Issue by timelyportfolio** [wch/webshot#8]
Thanks so much for this.  I discovered when working on `bower` in `htmlwidgets` that many Windows users might not have `PATH` set properly for node modules.  In these [lines](https://github.com/ramnathv/htmlwidgets/blob/master/R/scaffold.R#L185-L198), the search for `bower` just goes one level further.  The same could easily be used for `phantom`.  Happy to work into a pull if interested.

**Comment by wch** [comment]
Sure, I'm not sure I fully understand the problem, but I'll definitely look at a PR

**Comment by timelyportfolio** [comment]
Ok, I think I found one other issue with Windows.  Working on a pull now/
